import type { Metadata } from "next";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import 'antd/dist/reset.css'; 
import "react-toastify/dist/ReactToastify.css";
import '@ant-design/v5-patch-for-react-19';
import { NotificationProvider } from "@/contexts/NotificationContext";
export const metadata: Metadata = {
  title: "SGA&CD Legal Wing",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <head>
        <link rel="icon" type="image/png" href="/logo-green.png" />
      </head>
      <body>
        <NotificationProvider>
          {children}
        </NotificationProvider>
      </body>
    </html>
  );
}