// Court data for Supreme Court, Sindh High Courts, and District & Session Courts in Sindh

export const courtData: any = {
  supremecourt: [
    {
      courtName: "Main Registry – Islamabad",
      courtNumber: 150,
    },
    {
      courtName: "Karachi Registry",
      courtNumber: 150,
    },
    {
      courtName: "Other Branches Registry",
      courtNumber: 150,
    },
  ],
  highcourt: [
    {
      key: "sindhHighCourtKarachi",
      courtName: "Karachi High Court",
      courtNumber: 150,
    },
    {
      key: "sindhHighCourtHyderabad",
      courtName: "Hyderabad Bench",
      courtNumber: 150,
    },
    {
      key: "sindhHighCourtMirpurkhas",
      courtName: "Mirpurkhas Bench",
      courtNumber: 150,
      badge: "A",
    },
    {
      key: "sindhHighCourtLarkana",
      courtName: "Larkana Bench",
      courtNumber: 150,
      badge: "A",
    },
    {
      key: "sindhHighCourtSukkur",
      courtName: "Sukkur Bench",
      courtNumber: 150,
    },
    {
      courtName: "Other Provinces Highcourts",
      courtNumber: 150,
      badge: "A",
    },
  ],
  districtcourts: [
    { key: "badin", courtName: "District & Sessions Court Badin", courtNumber: 150 },
    { key: "dadu", courtName: "District & Sessions Court Dadu", courtNumber: 150 },
    { key: "ghotki", courtName: "District & Sessions Court Ghotki", courtNumber: 150 },
    { key: "hyderabad", courtName: "District & Sessions Court Hyderabad", courtNumber: 150 },
    { key: "jacobabad", courtName: "District & Sessions Court Jacobabad", courtNumber: 150 },
    { key: "jamshoroKotri", courtName: "District & Sessions Court Jamshoro (Kotri)", courtNumber: 150 },
    { key: "karachiCentral", courtName: "District & Sessions Court Karachi Central", courtNumber: 150 },
    { key: "karachiEast", courtName: "District & Sessions Court Karachi East", courtNumber: 150 },
    { key: "karachiSouth", courtName: "District & Sessions Court Karachi South", courtNumber: 150 },
    { key: "karachiWest", courtName: "District & Sessions Court Karachi West", courtNumber: 150 },
    { key: "keamari", courtName: "District & Sessions Court Keamari", courtNumber: 150 },
    { key: "korangi", courtName: "District & Sessions Court Korangi", courtNumber: 150 },
    { key: "karachiMalir", courtName: "District & Sessions Court Malir", courtNumber: 150 },
    { key: "kashmoreKandhkot", courtName: "District & Sessions Court Kashmore at Kandhkot", courtNumber: 150 },
    { key: "khairpur", courtName: "District & Sessions Court Khairpur", courtNumber: 150 },
    { key: "larkana", courtName: "District & Sessions Court Larkana", courtNumber: 150 },
    { key: "mirpurkhas", courtName: "District & Sessions Court Mirpurkhas", courtNumber: 150 },
    { key: "matiyari", courtName: "District & Sessions Court Matiari", courtNumber: 150 },
    { key: "naushahroFeroze", courtName: "District & Sessions Court Naushahro Feroze", courtNumber: 150 },
    { key: "kamberShahdadkot", courtName: "District & Sessions Court Qambar-Shahdadkot", courtNumber: 150 },
    { key: "sanghar", courtName: "District & Sessions Court Sanghar", courtNumber: 150 },
    { key: "shaheedBenazirabad", courtName: "District & Sessions Court Shaheed Benazirabad (Nawabshah)", courtNumber: 150 },
    { key: "shikarpur", courtName: "District & Sessions Court Shikarpur", courtNumber: 150 },
    { key: "sukkur", courtName: "District & Sessions Court Sukkur", courtNumber: 150 },
    { key: "tandoAllahyar", courtName: "District & Sessions Court Tando Allahyar", courtNumber: 150 },
    { key: "tandoMuhammadKhan", courtName: "District & Sessions Court Tando Muhammad Khan", courtNumber: 150 },
    { key: "tharparkarMithi", courtName: "District & Sessions Court Tharparkar at Mithi", courtNumber: 150 },
    { key: "thatta", courtName: "District & Sessions Court Thatta", courtNumber: 150 },
    { key: "umerkot", courtName: "District & Sessions Court Umerkot", courtNumber: 150 },
    { key: "sujawal", courtName: "District & Sessions Court Sujawal", courtNumber: 150 },
  ],
  othercourts: [
    { key: 'antiTerrorismCourts', courtName: 'Anti-Terrorism Courts', courtNumber: 150 },
    { key: 'antiCorruptionCourts', courtName: 'Anti Corruption Courts', courtNumber: 150 },
    { key: 'bankingCourts', courtName: 'Banking Courts', courtNumber: 150 },
    { key: 'labourCourts', courtName: 'Labour Courts', courtNumber: 150 },
    { key: 'specialCourtCNS', courtName: 'Special Court (CNS)', courtNumber: 150 },
    { key: 'appellateTribunalSindh', courtName: 'Appellate Tribunal Sindh', courtNumber: 150 },
    { key: 'revenueBoard', courtName: 'Revenue Board', courtNumber: 150 },
    { key: 'environmentalProtectionTribunal', courtName: 'Environmental Protection Tribunal', courtNumber: 150 },
    { key: 'accountabilityCourts', courtName: 'Accountability Courts', courtNumber: 150 },
    { key: 'customTaxationAntiSmugglingCourt', courtName: 'Custom, Taxation & Anti Smuggling Court', courtNumber: 150 },
    { key: 'drugCourt', courtName: 'Drug Court', courtNumber: 150 },
    { key: 'customsExciseSalesTaxAppellateTribunal', courtName: 'Customs, Excise & Sales Tax Appellate Tribunal', courtNumber: 150 },
    { key: 'specialCourtOffenceInBanks', courtName: 'Special Court (Offence in Banks)', courtNumber: 150 },
    { key: 'specialCourtCommercial', courtName: 'Special Court Commercial', courtNumber: 150 },
    { key: 'insuranceTribunal', courtName: 'Insurance Tribunal', courtNumber: 150 },
    { key: 'foreignExchangeAppellateTribunal', courtName: 'Foreign Exchange Appellate Tribunal', courtNumber: 150 },
    { key: 'removalOfAntiEncroachment', courtName: 'Removal of Anti Encroachment', courtNumber: 150 },
    { key: 'federalServiceTribunal', courtName: 'Federal Service Tribunal', courtNumber: 150 },
    { key: 'intellectualPropertyTribunal', courtName: 'Intellectual Property Tribunal', courtNumber: 150 },
    { key: 'appellateTribunalLocalCouncilsSindh', courtName: 'Appellate Tribunal Local Councils Sindh', courtNumber: 150 },
    { key: 'consumerProtectionCourt', courtName: 'Consumer Protection Court', courtNumber: 150 },
    { key: 'commercialCourtsMagistrate', courtName: 'Commercial Courts (Magistrate)', courtNumber: 150 },
    { key: 'gasTheftCourt', courtName: 'Gas Theft', courtNumber: 150 },
  ],
};
